version: "3"

services:
 acme-postgres:
  container_name: "acme-postgres"
  restart: unless-stopped
  image: "postgres:13"
  ports:
   - "15400:5432"
  volumes:
   - "pgdata:/var/lib/postgresql/data/"
  environment:
   POSTGRES_PASSWORD: postgres
 trusted-authority-postgres:
  container_name: "trusted-authority-postgres"
  restart: unless-stopped
  image: "postgres:13"
  ports:
   - "15401:5433"
  volumes:
   - "pgdata:/var/lib/postgresql/data/"
  environment:
   POSTGRES_PASSWORD: postgres

volumes:
 pgdata: {}
 my-db:
