version: "2"
services:
 indy_pool:
  build:
   context: ../../ci/
   dockerfile: indy-pool.dockerfile
   args:
    pool_ip: "10.0.0.2"
  image: indy_pool
  container_name: indy_pool
  working_dir: /home/indy
  ports:
   - "9701:9701"
   - "9702:9702"
   - "9703:9703"
   - "9704:9704"
   - "9705:9705"
   - "9706:9706"
   - "9707:9707"
   - "9708:9708"
  networks:
   pool_network:
    ipv4_address: 10.0.0.2
  volumes:
   - sandbox:/var/lib/indy/sandbox/
